#Service used for requesting to change the payload

string       payload         # Values allowed are UAV VISUAL PEC XR
---
bool        response_code   # Response true if all good, false if an error
string      response_msg    # Response message containing information